### ISSUE TITLE
Function traj_selection seems has some bugs

### ISSUE THREAD

**Issue by asanasdake** [Henry1iu/TNT-Trajectory-Predition#10]
Hi,

1. the threshold is halved for each while loop, it will soon fail to filter anything after a few while loops
2. traj_selected = traj_pred[:, :self.k]  should be traj_selected = traj_pred[:, :self.k] .clone()

**Comment by Henry1iu** [comment]
Hi,

Yes, you are right. Thanks for raising these issues. I will fix these bugs. @

Best Regards,
Jianbang
