### ISSUE TITLE
询问内存大小问题

### ISSUE THREAD

**Issue by yizhiweimengxiangfendoudefeifei** [Henry1iu/TNT-Trajectory-Predition#11]
Hello，您的意思是ram内存必须要大于110G吗？有没有什么办法可以减小内存的使用，因为课题组的电脑内存最大只有34G。顺便问一下，显卡3090，内存34G，可以进行训练吗？

**Comment by Henry1iu** [comment]
Hi,

你可以增加swap的容量, 3090显卡可以进行训练.
