### ISSUE TITLE
询问test_vectorNet

### ISSUE THREAD

**Issue by yizhiweimengxiangfendoudefeifei** [Henry1iu/TNT-Trajectory-Predition#12]
Hi,
请问有关vectorNet的推测没有被完成吗？  
这里我发现个错误，这两个参数是相同的，会报错。  
![屏幕截图 2022-05-05 112454](https://user-images.githubusercontent.com/39455551/166859525-96272b7e-5c4e-4cd8-aa6f-63aec80c93ea.png)

**Comment by Henry1iu** [comment]
Hi,

谢谢你的提醒, bug已经被修复. 

VectorNet的inference我没有写, 如果有需要的话可以参考tnt的inference,Vectornet的inference相对更简单.
