### ISSUE TITLE
Hardware requirements for model training

### ISSUE THREAD

**Issue by Thirteentj** [Henry1iu/TNT-Trajectory-Predition#13]
Hi！What are the hardware requirements for the training of this model? Thank you

**Comment by Henry1iu** [comment]
Hi,

I think all the computers installed with a GPU that is compatible with the CUDA 10.2 can be capable of the training of my implementation. The better your hardware is, the faster the training. 

As for the large dataset issue, if you are using a computer with NVME SSD, you can increase the size of the swap. Also, you can use the "ArgoverseInDisk" dataloader I implemented for the small memory devices. You can take a look at the "argoverse_loader_v2.py". 

Best Regards,
Jianbang

**Comment by Thirteentj** [comment]
That's OK. Thank you very much! My device has small memory. I'll try it.
