### ISSUE TITLE
fully connected subgraphs?

### ISSUE THREAD

**Issue by linaashaji** [Henry1iu/TNT-Trajectory-Predition#15]
Hello,

During constructing edge indices `(get_fc_edge_index --> _get_x method --> argoverse_loader_v2.py)`, I realized that you are building a fully connected graph for each cluster. However, as far as I understand your code, this cluster is constructed at the sub-graph level. So, shouldn't you connect the nodes according to the topology of the sub-graph? (e.g., the connections for the crosswalk are different from the connections in a regular lane). 

Thank you,
Lina

**Comment by Henry1iu** [comment]
Hi,

You can refer to Section 3.2 of the [(VectorNet paper)](https://openaccess.thecvf.com/content_CVPR_2020/html/Gao_VectorNet_Encoding_HD_Maps_and_Agent_Dynamics_From_Vectorized_Representation_CVPR_2020_paper.html). They constructed a fully connected graph at the subgraph level.

Your suggestion sounds more reasonable.  However, I did try to construct the subgraph according to the topology order. It showed worse performance. If you're interested, you can verify it yourself. If you find anything interesting, please do share it with me. :)

Best Regards,
Jianbang

**Comment by linaashaji** [comment]
Okay, thank you!
