### ISSUE TITLE
Is it convenient to provide the pre-trained weights of the model?

### ISSUE THREAD

**Issue by WhoAmI-kai** [Henry1iu/TNT-Trajectory-Predition#17]
Thank you very much for the open-source, is it convenient to provide the pre-trained weights of the model?

**Comment by Henry1iu** [comment]
Hi,

Actually, I'm still tuning the implementation of TNT model to achieve the performance reported in their paper. I will provide the pre-trained weights after I achieve the performance reported in the paper. 

For the pre-trained weights of VectorNet, I will find a way to share it. Thanks for reminding me. :)

Best,
Jianbang
