### ISSUE TITLE
Representation of vector node (feature)

### ISSUE THREAD

**Issue by legendjack** [Henry1iu/TNT-Trajectory-Predition#18]
Hi，感谢分享的代码，我注意到你使用**点和向量**表示折线的向量特征，而在yet_another_vectornet和VectorNet论文中（公式1）都是使用的start_point和end_point表示的向量特征；请问您使用点和向量是基于什么原因呢？

**Comment by legendjack** [comment]
另外我在train的时候发现Target_Offset_Loss一直在震荡，不下降，请问你遇到过这个问题吗？

**Comment by Henry1iu** [comment]
Hi,

关于输入的representation, 我认为我使用的representation与原作的区别不大 (只是一个linear transformation). 

Offset loss震荡的问题现在还有, 有可能是postive example太少的问题, 我还在调整模型试图解决, 请关注后续更新.

Best,
Jianbang
