### ISSUE TITLE
How can I get predicted trajectories with original coordibate?

### ISSUE THREAD

**Issue by Joe12138** [Henry1iu/TNT-Trajectory-Predition#2]
The data used in Network have been preprocessed, such as rotation, etc. Therefore, the predicted results are not in the coordinate in Argorverse dataset. Could you provide a script to reverse these operations?

**Comment by Henry1iu** [comment]
Dear Joe12138,

The corresponding feature has been added. You can check the latest version for detail (test_tnt.py).

Best regards,
Jianbang
