### ISSUE TITLE
数据预处理过慢

### ISSUE THREAD

**Issue by wangqf1997** [Henry1iu/TNT-Trajectory-Predition#21]
您好！

我们在使用您公开的代码时发现，数据预处理的过程非常慢，预计近百个小时，请问这是正常现象吗？
如果确实存在问题的话，请问该如何改善呢？

期待您的回答，谢谢！

(TNT) acl@acl-MS-7C98:~/TNT$ ./scripts/preprocessing.bash
  0%|                                    | 1/12872 [03:34<767:27:29, 214.66s/it]
  1%|▏                                    | 82/12872 [36:08<93:56:50, 26.44s/it]

**Comment by Henry1iu** [comment]
Hi,

请问你们使用的设备CPU型号是什么？我使用的设备CPU为i7 9900K，处理数据集大概需要48小时。刚开始的sequence处理时间会较长，稍后会有回落。

此致
剑邦

**Comment by wangqf1997** [comment]
您好！

数据处理是在我们的小型工作站上，CPU为i9-10900K，硬盘应该也是固态，具体记不清了。
这样看时间大概在合理的范围内，非常感谢您的解答。

**Comment by wanglaotou** [comment]
你好，我的cpu型号是：Intel(R) Xeon(R) Gold 5218R CPU @ 2.10GHz，执行：bash ./scripts/preprocessing.bash，显示处理数据时间需要5天，速度太慢了。
2%|▌                                | 198/12872 [1:59:22<115:48:59, 32.90s/it]

**Comment by Henry1iu** [comment]
> 你好，我的cpu型号是：Intel(R) Xeon(R) Gold 5218R CPU @ 2.10GHz，执行：bash ./scripts/preprocessing.bash，显示处理数据时间需要5天，速度太慢了。 2%|▌ | 198/12872 [1:59:22<115:48:59, 32.90s/it]

你好, 你的CPU主频比较低, 处理速度可能相对会慢一些. 你可以考虑加大batch_size和num_workers进行加速, 详情见[代码](https://github.com/Henry1iu/TNT-Trajectory-Prediction/blob/4c996808f4f6b9a2a12a62917c7f3647c74ed7a2/core/util/preprocessor/argoverse_preprocess_v2.py#L431). 

另外数据存储也会影响速度. 我没有在服务器上测试过速度, 具体情况需要你自行斟酌.
