### ISSUE TITLE
argoverse_preprocess_v2.py: error: unrecognized arguments: dataset/ dataset

### ISSUE THREAD

**Issue by owoshch** [Henry1iu/TNT-Trajectory-Predition#3]
Hi! I'm trying to preprocess argoverse data using the script `./scripts/preprocessing.bash` you provided.

Unfortunately, I'm getting the following error:

`~/repositories/TNT-Trajectory-Predition$ ./scripts/preprocessing.bash
usage: argoverse_preprocess_v2.py [-h] [-r ROOT] [-d DEST]
argoverse_preprocess_v2.py: error: unrecognized arguments: dataset/ dataset`

Could you guide me how to fix it, please?

Thank you

**Comment by owoshch** [comment]
Changed `-root` to `-r` and `-dest` to `-d` and it worked.
Closing the issue.

**Comment by Henry1iu** [comment]
Thanks for noticing. I have corrected the command in the script.
