### ISSUE TITLE
About TorchScript Model used to deploy in C++ or ONNX

### ISSUE THREAD

**Issue by rotk27** [Henry1iu/TNT-Trajectory-Predition#8]
Hi~ Do u have any plans to generate a TorchScript model which is jittable so that can be deployed on other platforms?  Recently I'm doing this work, but the GCN and lots of if-else makes me really suffers huh.

**Comment by Henry1iu** [comment]
Hi,

I'm afraid I not going to generate a TOrchScript. Wish you good luck with your work.

Best Regards,
Jianbang
