### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by DoubaoBelan** [Henry1iu/TNT-Trajectory-Predition#9]
Hi，

I have run scripts/preprocess.sh successfully. But when I run scripts/train_vectornet.sh, I got error looks like:
"
.conda/envs/vector_net/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 184, in _collate
and isinstance(elem[0], (Tensor, SparseTensor))):
IndexError: list index out of range
"

It looks like something went wrong in dataloader, but I did not know why.

**Comment by Henry1iu** [comment]
Hi,

How is the processing of the dataset? 

It seems that the initial processing of the dataset went wrong. Under the "train_intermedia" or "val_intermedia" folder, you should be able to find two folders named "processed" and "raw". If the initial processing of the dataset succeeds, you should find 3 files within the "processed" folder. The file named "data.pt" should be very large. 

If every thing I mentioned exists and looks good, I may need more detail to help you identify the issue. 

Best regards,
Jianbang

**Comment by soheilalizadeh** [comment]
I had the same issue. It happens when "candidate_mask" is empty.

Following this thread (https://github.com/pyg-team/pytorch_geometric/issues/3802), I manually changed the separate.py and collate.py in "pytorch_geometric" based on https://github.com/pyg-team/pytorch_geometric/pull/4293/files.

**Comment by Henry1iu** [comment]
> I had the same issue. It happens when "candidate_mask" is empty.
> 
> Following this thread ([pyg-team/pytorch_geometric#3802](https://github.com/pyg-team/pytorch_geometric/issues/3802)), I manually changed the separate.py and collate.py in "pytorch_geometric" based on https://github.com/pyg-team/pytorch_geometric/pull/4293/files.
> 
> which caused some other issue later:
> 
> ```
> train_Ep_0: loss: 0.00000e+00; avg_loss: 0.00000e+00:   0%|| 0/112 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "train_tnt.py", line 122, in <module>
>     train(args)
>   File "train_tnt.py", line 60, in train
>     _ = trainer.train(iter_epoch)
>   File "/home/kyber/projects/tnt/TNT-Trajectory-Predition/core/trainer/trainer.py", line 109, in train
>     return self.iteration(epoch, self.train_loader)
>   File "/home/kyber/projects/tnt/TNT-Trajectory-Predition/core/trainer/tnt_trainer.py", line 139, in iteration
>     for i, data in data_iter:
>   File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1171, in __iter__
>     for obj in iterable:
>   File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
>     data = self._next_data()
>   File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
>     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
>   File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
>     return self.collate_fn(data)
>   File "/opt/conda/lib/python3.8/site-packages/torch_geometric/loader/dataloader.py", line 19, in __call__
>     return Batch.from_data_list(batch, self.follow_batch,
>   File "/opt/conda/lib/python3.8/site-packages/torch_geometric/data/batch.py", line 68, in from_data_list
>     batch, slice_dict, inc_dict = collate(
>   File "/opt/conda/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 84, in collate
>     value, slices, incs = _collate(attr, values, data_list, stores,
>   File "/opt/conda/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 133, in _collate
>     incs = get_incs(key, values, data_list, stores)
>   File "/opt/conda/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 223, in get_incs
>     repeats = [
>   File "/opt/conda/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 224, in <listcomp>
>     data.__inc__(key, value, store)
> TypeError: __inc__() takes 3 positional arguments but 4 were given
> ```

What's the version of your torch_geometric lib? I'm using 1.7.2, and it's ok for me to make the "candidate_mask" empty.

**Comment by soheilalizadeh** [comment]
Thanks @Henry1iu. The issue is resolved after I used version 1.7.2 for both preprocessing and training.

**Comment by lion0819** [comment]
> Hi,
> 
> How is the processing of the dataset?
> 
> It seems that the initial processing of the dataset went wrong. Under the "train_intermedia" or "val_intermedia" folder, you should be able to find two folders named "processed" and "raw". If the initial processing of the dataset succeeds, you should find 3 files within the "processed" folder. The file named "data.pt" should be very large.
> 
> If everything I mentioned exists and looks good, I may need more detail to help you identify the issue.
> 
> Best regards, Jianbang

Hi,I also encountered this problem. I rechecked the dir file and did not find the "processed" folder and other files,such as "data.pt" or other files.How can I modify it to ensure that there is this folder.

**Comment by lion0819** [comment]
> > Hi,
> > How is the processing of the dataset?
> > It seems that the initial processing of the dataset went wrong. Under the "train_intermedia" or "val_intermedia" folder, you should be able to find two folders named "processed" and "raw". If the initial processing of the dataset succeeds, you should find 3 files within the "processed" folder. The file named "data.pt" should be very large.
> > If everything I mentioned exists and looks good, I may need more detail to help you identify the issue.
> > Best regards, Jianbang
> 
> Hi,I also encountered this problem. I rechecked the file and did not find the "processed" folder and other files,such as "data.pt" or other files.How can I modify it to ensure that there is this folder.
> 
> ```
> Traceback (most recent call last):
>   File "train_vectornet.py", line 9, in <module>
>     from torch_geometric.data import DataLoader
>   File "/home/simba/Software/anaconda3/envs/TNT/lib/python3.8/site-packages/torch_geometric/__init__.py", line 5, in <module>
>     import torch_geometric.data
>   File "/home/simba/Software/anaconda3/envs/TNT/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
>     from .data import Data
>   File "/home/simba/Software/anaconda3/envs/TNT/lib/python3.8/site-packages/torch_geometric/data/data.py", line 8, in <module>
>     from torch_sparse import coalesce, SparseTensor
>   File "/home/simba/Software/anaconda3/envs/TNT/lib/python3.8/site-packages/torch_sparse/__init__.py", line 41, in <module>
>     from .tensor import SparseTensor  # noqa
>   File "/home/simba/Software/anaconda3/envs/TNT/lib/python3.8/site-packages/torch_sparse/tensor.py", line 13, in <module>
>     class SparseTensor(object):
>   File "/home/simba/Software/anaconda3/envs/TNT/lib/python3.8/site-packages/torch/jit/_script.py", line 974, in script
>     _compile_and_register_class(obj, _rcb, qualified_name)
>   File "/home/simba/Software/anaconda3/envs/TNT/lib/python3.8/site-packages/torch/jit/_script.py", line 67, in _compile_and_register_class
>     torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
> RuntimeError: 
> Tried to access nonexistent attribute or method 'crow_indices' of type 'Tensor'.:
>   File "/home/simba/Software/anaconda3/envs/TNT/lib/python3.8/site-packages/torch_sparse/tensor.py", line 109
>     def from_torch_sparse_csr_tensor(self, mat: torch.Tensor,
>                                      has_value: bool = True):
>         rowptr = mat.crow_indices()
>                  ~~~~~~~~~~~~~~~~ <--- HERE
>         col = mat.col_indices()
> ```

This is my problem. Torch geometric is not installed correctly. Want to know your CUDA version? I installed "torch geometric" version 2.0.4.

**Comment by Henry1iu** [comment]
Hi, 

My CUDA version is 10.2. Also, I found it's difficult to install "torch_geomertric" with version 1.7.2. I list all the related lib with the version FYI. 

pytorch-cluster           1.5.9           py38_torch_1.8.0_cu102    rusty1s
pytorch-geometric         1.7.2           py38_torch_1.8.0_cu102    rusty1s
pytorch-scatter           2.0.7           py38_torch_1.8.0_cu102    rusty1s
pytorch-sparse            0.6.10          py38_torch_1.8.0_cu102    rusty1s
pytorch-spline-conv       1.2.1           py38_torch_1.8.0_cu102    rusty1s

Best Regards,
Jianbang

**Comment by hello-big-world** [comment]
> My torch_geomertric  version is 2.04 ,then nothing within the "processed" folder  and three xxx.pkl file within the "raw" folder.

**Comment by Henry1iu** [comment]
> 

Please use version 1.7.2 and do the preprocessing step as I mentioned in the README. There should be tones of files in the "raw" folder and 3 files in the "processed" folder. 

Three xxx.pkl file within the "raw" folder means you haven't finished the preprocessing.

Best Regards,
Jianbang
